#!/bin/bash

##############################################################################
# Script to build all docker files in this repository
##############################################################################

for DIRECTORY in `find . -maxdepth 1 -type d | sed '/^\.$/d'`
do
    if [[ "${DIRECTORY#./}" != ".git" ]]
    then
      echo -e "\033[0;32mBuilding ${DIRECTORY#./}...\033[0m"
      docker build -t thenodi/docker-${DIRECTORY#./}-valet:latest $DIRECTORY
    fi
done
